hispavista_web_homepage:
    pattern:  /
    defaults: { _controller: HispavistaWebBundle:Default:index }

hispavista_web_contact:
    pattern:  /contacto
    defaults: { _controller: HispavistaWebBundle:Contact:index }
    
genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"